### 2. Використовуючи датасет з файлу communities.csv, виконайте нормалізацію даних. Визначте найкращий метод нормалізації для даного набору даних.

In [38]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [39]:
train_data = pd.read_csv("communities.csv")
train_data

,8,?,?.1,Lakewoodcity,1,0.19,0.33,0.02,0.9,0.12,...,0.12.2,0.26.1,0.2.1,0.06.3,0.04.2,0.9.1,0.5.2,0.32.2,0.14.3,0.2.2
0,53,?,?,Tukwilacity,1,0.00,0.16,0.12,0.74,0.45,...,0.02,0.12,0.45,?,?,?,?,0.00,?,0.67
1,24,?,?,Aberdeentown,1,0.00,0.42,0.49,0.56,0.17,...,0.01,0.21,0.02,?,?,?,?,0.00,?,0.43
2,34,5,81440,Willingborotownship,1,0.04,0.77,1.00,0.08,0.12,...,0.02,0.39,0.28,?,?,?,?,0.00,?,0.12
3,42,95,6096,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,...,0.04,0.09,0.02,?,?,?,?,0.00,?,0.03
4,6,?,?,SouthPasadenacity,1,0.02,0.28,0.06,0.54,1.00,...,0.01,0.58,0.10,?,?,?,?,0.00,?,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,12,?,?,TempleTerracecity,10,0.01,0.40,0.10,0.87,0.12,...,0.01,0.28,0.05,?,?,?,?,0.00,?,0.09
1989,6,?,?,Seasidecity,10,0.05,0.96,0.46,0.28,0.83,...,0.02,0.37,0.20,?,?,?,?,0.00,?,0.45
1990,9,9,80070,Waterburytown,10,0.16,0.37,0.25,0.69,0.04,...,0.08,0.32,0.18,0.08,0.06,0.78,0,0.91,0.28,0.23
1991,25,17,72600,Walthamcity,10,0.08,0.51,0.06,0.87,0.22,...,0.03,0.38,0.33,0.02,0.02,0.79,0,0.22,0.18,0.19
1992,6,?,?,Ontariocity,10,0.20,0.78,0.14,0.46,0.24,...,0.11,0.30,0.05,0.08,0.04,0.73,0.5,1.00,0.13,0.48

Залишаємо лише числові дані

In [40]:
numeric_cols = [cname for cname in train_data.columns if train_data[cname].dtype in ['int64', 'float64']]
train_data = train_data[numeric_cols].copy()
train_data

,8,1,0.19,0.33,0.02,0.9,0.12,0.17,0.34,0.47,...,0.12.1,0.42,0.5.1,0.51.1,0.64,0.12.2,0.26.1,0.2.1,0.32.2,0.2.2
0,53,1,0.00,0.16,0.12,0.74,0.45,0.07,0.26,0.59,...,0.21,0.50,0.34,0.60,0.52,0.02,0.12,0.45,0.00,0.67
1,24,1,0.00,0.42,0.49,0.56,0.17,0.04,0.39,0.47,...,0.14,0.49,0.54,0.67,0.56,0.01,0.21,0.02,0.00,0.43
2,34,1,0.04,0.77,1.00,0.08,0.12,0.10,0.51,0.50,...,0.19,0.30,0.73,0.64,0.65,0.02,0.39,0.28,0.00,0.12
3,42,1,0.01,0.55,0.02,0.95,0.09,0.05,0.38,0.38,...,0.11,0.72,0.64,0.61,0.53,0.04,0.09,0.02,0.00,0.03
4,6,1,0.02,0.28,0.06,0.54,1.00,0.25,0.31,0.48,...,0.70,0.42,0.49,0.73,0.64,0.01,0.58,0.10,0.00,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,12,10,0.01,0.40,0.10,0.87,0.12,0.16,0.43,0.51,...,0.22,0.28,0.34,0.48,0.39,0.01,0.28,0.05,0.00,0.09
1989,6,10,0.05,0.96,0.46,0.28,0.83,0.32,0.69,0.86,...,0.53,0.25,0.17,0.10,0.00,0.02,0.37,0.20,0.00,0.45
1990,9,10,0.16,0.37,0.25,0.69,0.04,0.25,0.35,0.50,...,0.25,0.68,0.61,0.79,0.76,0.08,0.32,0.18,0.91,0.23
1991,25,10,0.08,0.51,0.06,0.87,0.22,0.10,0.58,0.74,...,0.45,0.64,0.54,0.59,0.52,0.03,0.38,0.33,0.22,0.19
1992,6,10,0.20,0.78,0.14,0.46,0.24,0.77,0.50,0.62,...,0.68,0.50,0.34,0.35,0.68,0.11,0.30,0.05,1.00,0.48

Визначаємо Х та у

In [41]:
X = train_data.drop("0.2.2", axis=1)
y = train_data["0.2.2"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#### Будуємо лінійну регресію та оцінюємо якість

In [42]:
lr = LinearRegression().fit(X_train, y_train)

print(f"Score for train set: {lr.score(X_train, y_train): .3f}")
print(f"Score for test set: {lr.score(X_test, y_test): .3f}")

Score for train set:  0.699
Score for test set:  0.671

#### L1 - Лассо

In [43]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.5).fit(X_train, y_train)
print(f"Lasso Regression-Training set score: {lasso.score(X_train, y_train):.3f}")
print(f"Lasso Regression-Test set score: {lasso.score(X_test, y_test):.3f}")

Lasso Regression-Training set score: 0.032
Lasso Regression-Test set score: 0.025

In [44]:
lasso = Lasso(alpha=0.01).fit(X_train, y_train)
print("Lasso Regression-Training set score: {:.3f}".format(lasso.score(X_train, y_train)))
print("Lasso Regression-Test set score: {:.3f}".format(lasso.score(X_test, y_test)))

Lasso Regression-Training set score: 0.568
Lasso Regression-Test set score: 0.568

#### L2 - Ridge

In [45]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.1).fit(X_train, y_train)
print(f"Ridge Regression-Training set score: {ridge.score(X_train, y_train):.3f}")
print(f"Ridge Regression-Test set score: {ridge.score(X_test, y_test):.3f}")

Ridge Regression-Training set score: 0.698
Ridge Regression-Test set score: 0.672

In [46]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=1).fit(X_train, y_train)
print(f"Ridge Regression-Training set score: {ridge.score(X_train, y_train):.3f}")
print(f"Ridge Regression-Test set score: {ridge.score(X_test, y_test):.3f}")

Ridge Regression-Training set score: 0.693
Ridge Regression-Test set score: 0.671

#### L1 + L2

In [47]:
from sklearn.linear_model import ElasticNet
elastic_net = ElasticNet(alpha=0.05, l1_ratio=0.05).fit(X_train, y_train)
print(f"Elastic Net-Training set score: {elastic_net.score(X_train, y_train):.3f}")
print(f"Elastic Net-Test set score: {elastic_net.score(X_test, y_test):.3f}")

Elastic Net-Training set score: 0.630
Elastic Net-Test set score: 0.626

In [48]:
from sklearn.linear_model import ElasticNet
elastic_net = ElasticNet(alpha=0.01, l1_ratio=0.01).fit(X_train, y_train)
print(f"Elastic Net-Training set score: {elastic_net.score(X_train, y_train):.3f}")
print(f"Elastic Net-Test set score: {elastic_net.score(X_test, y_test):.3f}")

Elastic Net-Training set score: 0.671
Elastic Net-Test set score: 0.661

#### Насправді ні один з методів нормалізації не привів до покращення показників нашої регресії. Якщо порівнювати результати роботи різних методів нормалізації, то найкращий результат в нашому прикладі показав метод L2 - Ridge.